import type { PGlite } from '@electric-sql/pglite';

/**
 * Browser-side migrations runner. The .sql files in this directory are
 * generated by `pnpm drizzle-kit generate` (see ../../../../drizzle.config.ts)
 * and bundled as raw strings; each is applied at most once, inside a
 * transaction, tracked in `haptic_migrations`. Failures surface — no
 * catch-and-ignore (the old runner swallowed every error).
 */
const migrationFiles = import.meta.glob<string>('./*.sql', {
  query: '?raw',
  import: 'default',
  eager: true
});

export interface MigrationResult {
  /** True when no migration had ever been applied before this boot (fresh database). */
  firstRun: boolean;
  /** Migration ids applied during this boot, in order. */
  appliedNow: string[];
}

export async function runMigrations(client: PGlite): Promise<MigrationResult> {
  await client.exec(
    `CREATE TABLE IF NOT EXISTS haptic_migrations (
      id text PRIMARY KEY,
      applied_at timestamptz NOT NULL DEFAULT now()
    )`
  );

  const applied = await client.query<{ id: string }>('SELECT id FROM haptic_migrations');
  const appliedIds = new Set(applied.rows.map((row) => row.id));
  const firstRun = appliedIds.size === 0;

  const migrations = Object.entries(migrationFiles)
    .map(([path, sql]) => ({ id: path.replace('./', '').replace(/\.sql$/, ''), sql }))
    .toSorted((a, b) => a.id.localeCompare(b.id));

  const appliedNow: string[] = [];
  for (const { id, sql } of migrations) {
    if (appliedIds.has(id)) {
      continue;
    }
    try {
      // oxlint-disable-next-line no-await-in-loop -- migrations must apply strictly in order
      await client.transaction(async (tx) => {
        for (const statement of sql.split('--> statement-breakpoint')) {
          const trimmed = statement.trim();
          if (trimmed) {
            // oxlint-disable-next-line no-await-in-loop -- statements run sequentially inside the transaction
            await tx.exec(trimmed);
          }
        }
        await tx.query('INSERT INTO haptic_migrations (id) VALUES ($1)', [id]);
      });
      appliedNow.push(id);
    } catch (error) {
      console.error(`Database migration "${id}" failed`, error);
      throw error;
    }
  }

  return { firstRun, appliedNow };
}
